main/default/objects/Integration_Logs__c/Integration_Logs__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Integration_Logs__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Integration_Logs__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time in which en event has occurred</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Integration_Logs__c/fields/End_point__c.field-meta.xml
<CustomField>
    <fullName>End_point__c</fullName>
    <description>Endpoint url</description>
    <label>End point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Integration_Logs__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Integration request type</description>
    <label>Request Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Integration_Logs__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Error response</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Integration_Logs__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who has requested</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/OAuth_Tokens__mdt/OAuth_Tokens__mdt.object-meta.xml
<CustomObject>
    <label>OAuth Token</label>
    <pluralLabel>OAuth Tokens</pluralLabel>
</CustomObject>

main/default/objects/OAuth_Tokens__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>The token</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/mcUtil.cls
public class mcUtil {
   
    public static map<String,String> getOAuthTokens(){
        map<string,string> mapNameToken = new Map<String,string>();

        for(OAuth_Tokens__mdt token : [Select id,developerName,token__c from OAuth_Tokens__mdt where developerName in ('Client_Secret','oAuth_ClientId','Google_oAuth_ClientId')]){
            mapNameToken.put(token.developerName,token.token__c);
        }

        return mapNameToken;
    }

    public static void logTransaction(String requestType, String url, String ConId, String response){
        Integration_Logs__c logRec = new Integration_Logs__c();
        logRec.Date__c = System.now();
        logRec.User__c = userInfo.getUserId();
        logRec.Response__c = response;
        logRec.Request_Type__c = requestType;
        logRec.End_point__c = url;
        logRec.Contact__c = ConId;
        Insert logRec;
    }
}